import {describe,it,expect} from 'vitest';
import {Repository} from '../electron/repository';
import {applyCommand} from '../electron/commands';
import {newItem} from '../shared/defaults';
describe('validated application commands',()=>{
 it('adds, edits, completes, trashes and restores an anytime task',()=>{const r=new Repository(':memory:');let item={...newItem('task',''),title:'Anytime'};applyCommand(r,{type:'item.save',item});expect(r.getData().items.find(i=>i.id===item.id)?.date).toBe('');item={...item,title:'Edited'};applyCommand(r,{type:'item.save',item});applyCommand(r,{type:'item.complete',id:item.id,date:'2026-10-08'});expect(r.getData().items.find(i=>i.id===item.id)?.done).toBe(true);applyCommand(r,{type:'item.delete',id:item.id});expect(r.getData().items.find(i=>i.id===item.id)?.deletedAt).toBeTruthy();applyCommand(r,{type:'item.restore',id:item.id});expect(r.getData().items.find(i=>i.id===item.id)?.deletedAt).toBe(null);r.close()});
 it('moves category items by category name during rename and delete',()=>{const r=new Repository(':memory:');const categories=r.getData().categories.map(c=>c.name==='Study'?{...c,name:'Learning'}:c);applyCommand(r,{type:'categories.save',categories,moveFrom:'Study',moveTo:'Learning'});expect(r.getData().items.find(i=>i.title==='Lesson plan')?.category).toBe('Learning');applyCommand(r,{type:'categories.save',categories:categories.filter(c=>c.name!=='Learning'),moveFrom:'Learning',moveTo:'Other'});expect(r.getData().items.find(i=>i.title==='Lesson plan')?.category).toBe('Other');r.close()});
 it('queues offline changes atomically and keeps local occurrence edits independent',()=>{const r=new Repository(':memory:');const item={...newItem('task','2026-10-08'),title:'Daily',repeat:'Daily' as const};applyCommand(r,{type:'item.save',item});applyCommand(r,{type:'item.save',item:{...item,title:'Single edit'},scope:'occurrence',occurrenceDate:'2026-10-09'});expect(r.getData().items.find(i=>i.id===item.id)?.exceptions['2026-10-09'].title).toBe('Single edit');const synced={...newItem('event','2026-10-08'),title:'Offline event',synced:true};applyCommand(r,{type:'item.save',item:synced});expect(r.listOutbox().map(x=>x.itemId)).toContain(synced.id);expect(r.getData().items.find(i=>i.id===synced.id)?.syncState).toBe('Pending sync');expect(()=>applyCommand(r,{type:'item.save',item:{...synced,title:'Unsafe override'},scope:'occurrence',occurrenceDate:'2026-10-09'})).toThrow('Google-linked');r.close()});
 it('validates main-process inputs and persists focus pause, resume, ordering and settings',()=>{const r=new Repository(':memory:');expect(()=>applyCommand(r,{type:'arbitrary.execute',path:'cmd'})).toThrow();const ids=r.getData().items.map(i=>i.id).reverse();applyCommand(r,{type:'item.reorder',ids});expect(r.getData().items.find(i=>i.id===ids[0])?.order).toBe(0);applyCommand(r,{type:'focus.action',action:'configure',duration:45});applyCommand(r,{type:'focus.action',action:'start'});expect(r.getData().focus.deadline).toBeGreaterThan(Date.now());applyCommand(r,{type:'focus.action',action:'pause'});expect(r.getData().focus.running).toBe(false);applyCommand(r,{type:'focus.action',action:'resume'});expect(r.getData().focus.running).toBe(true);applyCommand(r,{type:'settings.save',settings:{...r.getData().settings,time:'24'}});expect(r.getData().settings.time).toBe('24');r.close()});
});
