import {describe,it,expect} from 'vitest';
import {iso,shift,validateItem,occurrenceItems,isDone,toggleCompletion,toRRule,scheduledAt,parseQuick,calendarLanes,focusRemaining,advanceFocus} from '../shared/domain';
import {newItem,defaultSettings,createInitialData} from '../shared/defaults';
import type {FocusState,Item} from '../shared/types';
const item=(p:Partial<Item>={}):Item=>({...newItem('task','2026-01-31'),title:'Test',...p});
describe('calendar dates and recurrence',()=>{
 it('shifts dates through leap days without UTC conversion',()=>{expect(shift('2024-02-28',1)).toBe('2024-02-29');expect(iso(new Date(2026,0,3))).toBe('2026-01-03')});
 it('skips impossible monthly days and counts valid occurrences',()=>{const x=item({repeat:'Monthly',recurrenceCount:2});expect(occurrenceItems([x],'2026-02-28')).toHaveLength(0);expect(occurrenceItems([x],'2026-03-31')).toHaveLength(1);expect(occurrenceItems([x],'2026-05-31')).toHaveLength(0)});
 it('skips non leap years',()=>{const x=item({date:'2024-02-29',repeat:'Yearly'});expect(occurrenceItems([x],'2025-02-28')).toHaveLength(0);expect(occurrenceItems([x],'2028-02-29')).toHaveLength(1)});
 it('honors interval, inclusive end, exclusions, exceptions and trash',()=>{const x=item({date:'2026-10-05',repeat:'Daily',interval:2,recurrenceEnd:'2026-10-09',excludedDates:['2026-10-07'],exceptions:{'2026-10-09':{title:'Changed'}}});expect(occurrenceItems([x],'2026-10-07')).toEqual([]);expect(occurrenceItems([x],'2026-10-09')[0].title).toBe('Changed');expect(occurrenceItems([x],'2026-10-11')).toEqual([]);expect(occurrenceItems([{...x,deletedAt:'now'}],'2026-10-05')).toEqual([])});
 it('supports weekday and weekly recurrence',()=>{expect(occurrenceItems([item({date:'2026-10-05',repeat:'Weekdays'})],'2026-10-10')).toEqual([]);expect(occurrenceItems([item({date:'2026-10-05',repeat:'Weekly',interval:2})],'2026-10-19')).toHaveLength(1)});
 it('counts a partial weekday week before later interval weeks',()=>{const x=item({date:'2026-10-07',repeat:'Weekdays',interval:2,recurrenceCount:4});expect(occurrenceItems([x],'2026-10-12')).toHaveLength(0);expect(occurrenceItems([x],'2026-10-19')).toHaveLength(1);expect(occurrenceItems([x],'2026-10-20')).toHaveLength(0)});
 it('moves an exception without showing both dates and retains independent completion identities',()=>{const x=item({repeat:'Daily',exceptions:{'2026-02-01':{date:'2026-02-04',title:'Moved'}}});expect(occurrenceItems([x],'2026-02-01')).toHaveLength(0);const occurrences=occurrenceItems([x],'2026-02-04');expect(occurrences.map(x=>x.title)).toEqual(['Test','Moved']);expect(occurrences.map(x=>x.occurrenceDate)).toEqual(['2026-02-04','2026-02-01']);const toggled=toggleCompletion(occurrences[1],occurrences[1].date);expect(toggled.completedDates).toEqual(['2026-02-01']);expect(isDone(toggleCompletion(x,'2026-02-04'),'2026-02-01')).toBe(false)});
 it('serializes count and end together using the earliest single bound',()=>{const x=item({date:'2026-10-07',repeat:'Weekdays',interval:2,recurrenceCount:10,recurrenceEnd:'2026-10-19'});expect(toRRule(x)[0]).toContain('COUNT=4');expect(toRRule(x)[0]).not.toContain('UNTIL=')});
 it('independently toggles occurrence completion without mutating input',()=>{const x=item({repeat:'Daily'});const y=toggleCompletion(x,'2026-02-01');expect(isDone(y,'2026-02-01')).toBe(true);expect(isDone(y,'2026-02-02')).toBe(false);expect(x.completedDates).toEqual([]);expect(isDone(toggleCompletion(y,'2026-02-01'),'2026-02-01')).toBe(false)});
 it('exports timezone-aware Google recurrence and exclusions',()=>{const rule=toRRule(item({repeat:'Daily',time:'09:00',timezone:'America/New_York',recurrenceEnd:'2026-02-02',excludedDates:['2026-02-01']}));expect(rule.join('\n')).toContain('UNTIL=20260203T045959Z');expect(rule.join('\n')).toContain('EXDATE;TZID=America/New_York:20260201T090000');expect(toRRule(item({repeat:'Daily',excludedDates:['2026-02-01']})).join('\n')).toContain('EXDATE;VALUE=DATE:20260201')});
});
describe('validation and scheduling',()=>{
 it('schedules a date-only local reminder at nine in its own time zone',()=>expect(new Date(scheduledAt(item({time:'',timezone:'UTC'}),'2026-10-08')).toISOString()).toBe('2026-10-08T09:00:00.000Z'));
 it('accepts undated anytime tasks but requires dates for recurrence and synchronization',()=>{expect(validateItem(item({date:'',time:'',repeat:'Never'})).date).toBe('');expect(()=>validateItem(item({date:'',repeat:'Daily'}))).toThrow();expect(()=>validateItem(item({date:'',synced:true}))).toThrow()});
 it.each([{date:'2026-02-30'},{time:'25:00'},{time:'10:00',end:'09:00'},{timezone:'Moon/Base'},{reminders:[40321]},{reminders:[1,2,3,4,5,6]},{title:' '},{interval:0}])('rejects malformed schedule %j',p=>expect(()=>validateItem(item(p))).toThrow());
 it('trims title and accepts an all day item',()=>expect(validateItem(item({title:' Fine ',time:'',end:''})).title).toBe('Fine'));
 it('maintains wall-clock time across daylight saving',()=>{const x=item({time:'09:00',timezone:'America/New_York'});expect(new Date(scheduledAt(x,'2026-03-07')).toISOString()).toBe('2026-03-07T14:00:00.000Z');expect(new Date(scheduledAt(x,'2026-03-08')).toISOString()).toBe('2026-03-08T13:00:00.000Z')});
 it('moves nonexistent DST time forward and chooses first ambiguous time',()=>{const x=item({time:'02:30',timezone:'America/New_York'});expect(new Date(scheduledAt(x,'2026-03-08')).toISOString()).toBe('2026-03-08T07:30:00.000Z');expect(new Date(scheduledAt({...x,time:'01:30'},'2026-11-01')).toISOString()).toBe('2026-11-01T05:30:00.000Z')});
 it('parses quick dates, 12 hour times, priority and recurrence',()=>expect(parseQuick('Read tomorrow at 3:30pm daily !high','2026-10-08')).toMatchObject({title:'Read',date:'2026-10-09',time:'15:30',repeat:'Daily',priority:'High'}));
 it('retains unrecognized quick input',()=>expect(parseQuick('Read my book','2026-10-08')).toMatchObject({title:'Read my book',date:'2026-10-08'}));
 it('parses the supplied quick-add example including a compact reminder unit',()=>expect(parseQuick('Gym tomorrow 6pm remind me 30m before','2026-10-08')).toMatchObject({title:'Gym',date:'2026-10-09',time:'18:00',reminders:[30],reminderEnabled:true}));
 it('lays out overlapping blocks across hour boundaries',()=>{const result=calendarLanes([item({id:'a',time:'09:45',end:'11:00'}),item({id:'b',time:'10:00',end:'10:30'}),item({id:'c',time:'11:00',end:'12:00'})]);expect(result.find(x=>x.id==='a')).toMatchObject({lane:0,lanes:2});expect(result.find(x=>x.id==='b')).toMatchObject({lane:1,lanes:2});expect(result.find(x=>x.id==='c')).toMatchObject({lane:0,lanes:1})});
});
describe('focus and defaults',()=>{
 const f:FocusState={duration:25,remaining:1500,deadline:10000,running:true,task:'a',goal:'Read',sessionId:'session',history:[]};
 it('derives countdown from durable deadline',()=>expect(focusRemaining(f,8500)).toBe(2));
 it('records an elapsed focus session exactly once',()=>{const result=advanceFocus(f,12000);expect(result.completed).toBe(true);expect(result.focus.history[0]).toMatchObject({id:'session',minutes:25,completedAt:10000});expect(advanceFocus(result.focus,15000).completed).toBe(false);expect(f.history).toEqual([])});
 it('creates only local seeded data and independent defaults',()=>{const d=createInitialData();expect(d.items.length).toBeGreaterThan(0);expect(d.items.every(x=>!x.synced&&x.syncState==='Local only')).toBe(true);expect(defaultSettings().defaultReminders).toEqual([10]);expect(newItem().id).not.toBe(newItem().id)});
});
