import {describe,it,expect,vi} from 'vitest';
import {createHash} from 'node:crypto';
import {GoogleService,itemToGoogle,type GoogleRepository} from '../electron/google';
import {createInitialData,newItem} from '../shared/defaults';
import type {AppData} from '../shared/types';
const secure={isEncryptionAvailable:()=>true,encryptString:(s:string)=>Buffer.from('encrypted:'+s),decryptString:(b:Buffer)=>b.toString().slice(10)};
function fixture(){let data=createInitialData();data.items=[];data.settings.googleClientId='desktop-client';data.settings.calendarId='calendar';data.settings.syncMode='push';const meta=new Map<string,unknown>();let queue:{id:number;itemId:string;action:'upsert'|'delete';attempts:number;error:string}[]=[];let seq=0;const repo:GoogleRepository={getData:()=>structuredClone(data),update:fn=>{fn(data);return structuredClone(data)},getMeta:<T>(key:string)=>meta.get(key) as T|undefined,setMeta:(key,value)=>{meta.set(key,value)},enqueue:(itemId,action='upsert')=>{queue.push({id:++seq,itemId,action,attempts:0,error:''})},listOutbox:()=>structuredClone(queue),removeOutbox:id=>{queue=queue.filter(e=>e.id!==id)},failOutbox:(id,error)=>{const row=queue.find(e=>e.id===id)!;row.attempts++;row.error=error;}};meta.set('google.tokens.encrypted',secure.encryptString(JSON.stringify({access_token:'access',refresh_token:'refresh',expiresAt:9999999999999})).toString('base64'));return{repo,meta,get data(){return data}};}
const json=(value:unknown,status=200,headers?:HeadersInit)=>new Response(status===204?null:JSON.stringify(value),{status,headers});
function http(handler:(url:string,init:RequestInit)=>Response|Promise<Response>){return vi.fn(async (url:RequestInfo|URL,init:RequestInit={})=>{if(String(url).includes('/calendarList'))return json({items:[{id:'calendar',summary:'Personal',accessRole:'owner'}]});return handler(String(url),init)}) as unknown as typeof globalThis.fetch;}
describe('Google Calendar HTTP integration',()=>{
 it('preserves date-only values and exports timezone recurrence, refuses unsupported edits',()=>{const item={...newItem('task','2026-10-08'),title:'All day',time:'',end:'',repeat:'Daily' as const};expect(itemToGoogle(item)).toMatchObject({start:{date:'2026-10-08'},end:{date:'2026-10-09'}});expect(itemToGoogle({...item,time:'09:00',timezone:'America/New_York',excludedDates:['2026-10-09']}).recurrence?.join('\n')).toContain('EXDATE;TZID=America/New_York:20261009T090000');expect(()=>itemToGoogle({...item,exceptions:{'2026-10-10':{title:'Edited'}}})).toThrow('not supported');});
 it('only marks synced after HTTP success and uses deterministic event IDs on duplicate retry',async()=>{const f=fixture(),item={...newItem('task','2026-10-08'),title:'Test',synced:true};f.data.items.push(item);f.repo.enqueue(item.id);let uploaded:any;const fetch=http((url,init)=>{if(init.method==='POST'){uploaded=JSON.parse(String(init.body));return json({},409);}return json({...uploaded,etag:'"etag"',updated:'2026-10-08T12:00:00Z'});});await new GoogleService(f.repo,{safeStorage:secure,openExternal:async()=>{},fetch}).sync();expect(uploaded.id).toBe('mt'+createHash('sha256').update(item.id).digest('hex'));expect(f.data.items[0].syncState).toBe('Synced');expect(f.repo.listOutbox()).toHaveLength(0);});
 it('retains failed upload and honors Retry-After without claiming success',async()=>{const f=fixture();const item={...newItem('task','2026-10-08'),synced:true};f.data.items.push(item);f.repo.enqueue(item.id);const fetch=http(()=>json({},429,{'Retry-After':'120'}));const service=new GoogleService(f.repo,{safeStorage:secure,openExternal:async()=>{},fetch,now:()=>1000});await service.sync();expect(f.data.items[0].syncState).toBe('Sync error');expect(f.repo.listOutbox()[0].attempts).toBe(1);const count=(fetch as any).mock.calls.length;await service.sync();expect((fetch as any).mock.calls.length).toBe(count+1);expect(f.meta.get('google.retry.1')).toBe(121000);});
 it('keeps ETag collisions reviewable and local resolution requeues against latest etag',async()=>{const f=fixture();const item={...newItem('event','2026-10-08'),title:'Local',synced:true,calendarId:'calendar',remoteId:'remote',remoteEtag:'old'};f.data.items.push(item);f.repo.enqueue(item.id);const fetch=http((_url,init)=>init.method==='PUT'?json({},412):json({...itemToGoogle(item),id:'remote',etag:'new',summary:'Remote'}));const service=new GoogleService(f.repo,{safeStorage:secure,openExternal:async()=>{},fetch});await service.sync();expect(f.data.conflicts[0].remote.title).toBe('Remote');expect(f.data.items[0].syncState).toBe('Conflict');await service.resolveConflict(f.data.conflicts[0].id,'local');expect(f.data.items[0]).toMatchObject({title:'Local',remoteEtag:'new',syncState:'Pending sync'});expect(f.repo.listOutbox()).toHaveLength(1);});
 it('refreshes credentials using HTTP and only persists encrypted token blobs',async()=>{const f=fixture();f.meta.set('google.tokens.encrypted',secure.encryptString(JSON.stringify({access_token:'expired',refresh_token:'refresh',expiresAt:0})).toString('base64'));const fetch=vi.fn(async(url:RequestInfo|URL,init:RequestInit={})=>{if(String(url).endsWith('/token')){expect(String(init.body)).toContain('refresh_token=refresh');return json({access_token:'renewed',expires_in:3600});}expect((init.headers as any).Authorization).toBe('Bearer renewed');return json({items:[]});}) as unknown as typeof globalThis.fetch;await new GoogleService(f.repo,{safeStorage:secure,openExternal:async()=>{},fetch}).sync();expect(String(f.meta.get('google.tokens.encrypted'))).not.toContain('renewed');expect(secure.decryptString(Buffer.from(String(f.meta.get('google.tokens.encrypted')),'base64'))).toContain('renewed');});
 it('restarts expired sync tokens and follows pages without importing existing events by default',async()=>{const f=fixture();f.data.settings.syncMode='two-way';f.meta.set('google.syncToken.calendar','expired');let pages=0;const fetch=http(url=>{if(url.includes('syncToken=expired'))return json({},410);pages++;return pages===1?json({items:[{id:'foreign',summary:'Private',start:{date:'2026-10-08'},end:{date:'2026-10-09'}}],nextPageToken:'page2'}):json({items:[],nextSyncToken:'fresh'});});await new GoogleService(f.repo,{safeStorage:secure,openExternal:async()=>{},fetch}).sync();expect(f.data.items).toEqual([]);expect(f.meta.get('google.syncToken.calendar')).toBe('fresh');expect(pages).toBe(2);});
 it('uses system-browser PKCE, rejects wrong state, stores actual account, and closes loopback',async()=>{const f=fixture();f.meta.delete('google.tokens.encrypted');let redirect='';const fetch=http(url=>{if(url.endsWith('/token'))return json({access_token:'new',refresh_token:'refresh',expires_in:3600});if(url.includes('userinfo'))return json({email:'real@example.com'});return json({items:[]});});const service=new GoogleService(f.repo,{safeStorage:secure,fetch,openExternal:async(raw)=>{const auth=new URL(raw);expect(auth.searchParams.get('code_challenge_method')).toBe('S256');redirect=auth.searchParams.get('redirect_uri')!;expect(new URL(redirect).hostname).toBe('127.0.0.1');expect((await globalThis.fetch(`${redirect}?state=wrong&code=bad`)).status).toBe(400);await globalThis.fetch(`${redirect}?state=${auth.searchParams.get('state')}&code=valid`);}});await service.connect();expect(f.data.google).toMatchObject({connected:true,account:'real@example.com'});await expect(globalThis.fetch(redirect)).rejects.toThrow();});
 it('refuses sign-in when OS encryption is unavailable',async()=>{const f=fixture();const openExternal=vi.fn();const service=new GoogleService(f.repo,{safeStorage:{...secure,isEncryptionAvailable:()=>false},openExternal});await expect(service.connect()).rejects.toThrow('secure credential storage');expect(openExternal).not.toHaveBeenCalled();});
 it('imports only from the selected calendar and does not echo imports back to Google',async()=>{const f=fixture();f.data.settings.syncMode='two-way';f.data.settings.importExisting=true;const fetch=http((_url,init)=>{expect(init.method).toBeUndefined();return json({items:[{id:'remote',etag:'v1',summary:'Imported',start:{date:'2026-10-08'},end:{date:'2026-10-09'}}],nextSyncToken:'token'});});const service=new GoogleService(f.repo,{safeStorage:secure,openExternal:async()=>{},fetch});await service.sync();expect(f.data.items[0]).toMatchObject({title:'Imported',date:'2026-10-08',time:'',remoteId:'remote',syncState:'Synced'});expect(f.repo.listOutbox()).toHaveLength(0);await service.sync();expect(f.data.items).toHaveLength(1);});
 it('honors unlink preference and avoids importing the unlinked Google event again',async()=>{const f=fixture();f.data.settings.syncMode='two-way';f.data.settings.importExisting=true;f.data.settings.deleteGoogle=false;const item={...newItem('event','2026-10-08'),title:'Unlink',synced:false,calendarId:'calendar',remoteId:'remote',remoteEtag:'v1'};f.data.items.push(item);f.repo.enqueue(item.id,'delete');const fetch=http((_url,init)=>{expect(init.method).not.toBe('DELETE');return json({items:[{...itemToGoogle(item),id:'remote',etag:'v1'}],nextSyncToken:'token'});});await new GoogleService(f.repo,{safeStorage:secure,openExternal:async()=>{},fetch}).sync();expect(f.data.items).toHaveLength(1);expect(f.data.items[0]).toMatchObject({synced:false,remoteId:'',syncState:'Local only'});});
 it('revokes the Google credential and always removes its encrypted local copy',async()=>{const f=fixture();const fetch=vi.fn(async(url:RequestInfo|URL,init:RequestInit={})=>{expect(String(url)).toContain('/revoke');expect(String(init.body)).toBe('token=refresh');return json({});}) as unknown as typeof globalThis.fetch;await new GoogleService(f.repo,{safeStorage:secure,openExternal:async()=>{},fetch}).disconnect();expect(f.data.google.connected).toBe(false);expect(f.meta.get('google.tokens.encrypted')).toBeNull();});
});
