/* Local data and replaceable integration services. No network calls. */
const Store=(()=>{
 const key='enchanted-my-tasks-v1';
 const iso=(d=new Date())=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
 const shift=(date,n)=>{const d=new Date(date+'T12:00:00');d.setDate(d.getDate()+n);return iso(d)};
 const today=iso();
 const defaults={categories:[['Personal','leaf'],['Study','book-open'],['Work','laptop'],['Gym','dumbbell'],['Health','heart-pulse'],['Routine','moon'],['Appointments','calendar-check'],['Social','users'],['Shopping','shopping-bag'],['Other','sparkles']].map(([name,icon],i)=>({id:'cat'+i,name,icon})),settings:{start:'Home',time:'12',week:'Monday',connected:false,calendar:'My Tasks',sync:'Two-way sync',defaultReminder:30,syncCompleted:false,deleteGoogle:true,desktop:true,googleNotify:true,sound:false},focus:{seconds:1500,mode:25,sessions:0,minutes:0,goal:'One small step forward',task:''},items:[]};
 const sample=[['Lesson plan','09:00','Study',true],['Gym','11:00','Gym',false],['Edit video','14:00','Work',true],['Read a chapter','18:00','Study',false],['Skincare','20:00','Routine',false],['Bedtime','22:00','Routine',false]];
 defaults.items=sample.map(([title,time,category,done],i)=>({id:'seed'+i,title,date:today,time,end:'',category,done,kind:'task',priority:'Normal',repeat:'Never',interval:2,reminders:i===1?[30]:i===4?[10]:[],reminderEnabled:true,synced:false,notes:'',location:'',order:i,completedDates:[]}));
 const weekday=(n)=>{const d=new Date(today+'T12:00:00');let delta=(n-d.getDay()+7)%7;return shift(today,delta||7)};
 [['Dentist Appointment',shift(today,1),'15:00','16:00','Health',true,'Dental clinic'],['University Lecture',weekday(4),'10:00','12:00','Study',false,'University campus'],['Dinner',weekday(5),'20:00','21:00','Personal',false,'']].forEach(([title,date,time,end,category,synced,location],i)=>defaults.items.push({id:'event'+i,title,date,time,end,category,synced,location,done:false,kind:'event',priority:'Normal',repeat:'Never',interval:2,reminders:[30],reminderEnabled:true,notes:'',order:6+i,completedDates:[]}));
 let data;try{data=JSON.parse(localStorage.getItem(key))}catch{}if(!data||!Array.isArray(data.items)||!Array.isArray(data.categories))data=structuredClone(defaults);
 const persist=()=>{try{localStorage.setItem(key,JSON.stringify(data));return true}catch{return false}};
 const matches=(t,date)=>{if(!t.date)return false;if(date<t.date)return false;if(t.repeat==='Never')return date===t.date;const a=new Date(t.date+'T12:00:00'),b=new Date(date+'T12:00:00'),days=Math.round((Date.UTC(b.getFullYear(),b.getMonth(),b.getDate())-Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()))/86400000);return t.repeat==='Daily'||t.repeat==='Weekdays'&&b.getDay()>0&&b.getDay()<6||t.repeat==='Weekly'&&days%7===0||t.repeat==='Monthly'&&a.getDate()===b.getDate()||t.repeat==='Yearly'&&a.getDate()===b.getDate()&&a.getMonth()===b.getMonth()||t.repeat==='Custom'&&days%Math.max(1,Number(t.interval)||1)===0};
 const on=(date)=>data.items.filter(t=>matches(t,date)).sort((a,b)=>a.order-b.order);
 const done=(t,date)=>t.repeat==='Never'?t.done:(t.completedDates||[]).includes(date);
 const toggle=(id,date)=>{const t=data.items.find(x=>x.id===id);if(!t)return;if(t.repeat==='Never')t.done=!t.done;else{t.completedDates??=[];t.completedDates=done(t,date)?t.completedDates.filter(x=>x!==date):[...t.completedDates,date]}persist()};
 return {get data(){return data},today,iso,shift,on,done,matches,persist,toggle,reset(){data=structuredClone(defaults);persist()},replace(next){data=next;persist()}};
})();
const CalendarService={async connect(){await new Promise(r=>setTimeout(r,450));Store.data.settings.connected=true;Store.persist();return {account:'johan@example.com',simulated:true}},async disconnect(){Store.data.settings.connected=false;Store.persist()},sync(item){return {id:'mock-'+item.id,status:Store.data.settings.connected?'simulated-synced':'pending-connection',simulated:true}}};
const NotificationService={snooze(item,minutes=10){item.snoozeUntil=Date.now()+minutes*60000;Store.persist()},due(item,now=Date.now()){if(!item.reminderEnabled||!item.time)return false;return item.reminders.some(m=>{const at=new Date(item.date+'T'+item.time).getTime()-m*60000;return now>=at&&now<at+60000})},play(){if(!Store.data.settings.sound)return;try{const c=new (window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.frequency.value=660;g.gain.value=.05;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.15)}catch{}}};
