import {useEffect,useRef,useState} from 'react';
import type {AppData,Item} from '../shared/types';
import {iso,shift,occurrenceItems,calendarLanes} from '../shared/domain';
import {IconButton,humanDate,clockTime,mins,hm} from './ui';
type View='Day'|'Week'|'Month';
export default function Calendar({data,date,setDate,open,create,move,progress}:{data:AppData;date:string;setDate:(d:string)=>void;open:(i:Item,d:string)=>void;create:(d:string,t?:string)=>void;move:(i:Item,date:string,time:string,end:string)=>void;progress:React.ReactNode}){
 const [view,setView]=useState<View>('Week'),[drag,setDrag]=useState<Item|null>(null);const scroller=useRef<HTMLDivElement>(null);
 const first=data.settings.week==='Monday'?1:0;
 const weekStart=(d:string)=>shift(d,-((new Date(d+'T12:00:00').getDay()-first+7)%7));
 const dates=view==='Day'?[date]:Array.from({length:7},(_,i)=>shift(weekStart(date),i));
 const step=(n:number)=>{if(view==='Month'){const d=new Date(date+'T12:00:00');d.setDate(1);d.setMonth(d.getMonth()+n);setDate(iso(d))}else setDate(shift(date,n*(view==='Week'?7:1)))};
 useEffect(()=>{if(scroller.current&&view!=='Month')scroller.current.scrollTop=8*56},[view]);
 const drop=(d:string,min:number)=>{if(!drag)return;const duration=drag.end?mins(drag.end)-mins(drag.time):60;const start=Math.min(1440-duration-1,Math.max(0,min));move(drag,d,hm(start),hm(start+duration));setDrag(null)};
 const resize=(e:React.PointerEvent,item:Item)=>{e.stopPropagation();e.preventDefault();const initial=mins(item.end||hm(Math.min(1439,mins(item.time)+60)))-mins(item.time),start=e.clientY;const element=e.currentTarget.parentElement!;let duration=initial;const motion=(ev:PointerEvent)=>{duration=Math.min(1439-mins(item.time),Math.max(15,Math.round((initial+(ev.clientY-start)/56*60)/15)*15));element.style.height=`${duration/60*56-3}px`};const finish=()=>{document.removeEventListener('pointermove',motion);document.removeEventListener('pointerup',finish);move(item,item.date,item.time,hm(mins(item.time)+duration))};document.addEventListener('pointermove',motion);document.addEventListener('pointerup',finish,{once:true})};
 const labels=first?['Mon','Tue','Wed','Thu','Fri','Sat','Sun']:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
 const month=new Date(date+'T12:00:00'),monthStart=weekStart(iso(new Date(month.getFullYear(),month.getMonth(),1)));
 return <><div className="toolbar"><IconButton icon="chevron-left" label="Previous period" onClick={()=>step(-1)}/><button className="secondary" onClick={()=>setDate(iso())}>Today</button><IconButton icon="chevron-right" label="Next period" onClick={()=>step(1)}/><input type="date" aria-label="Calendar date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/><span className="period-label">{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</span><div className="segmented" aria-label="Calendar view">{(['Day','Week','Month'] as View[]).map(v=><button key={v} className={v===view?'active':''} onClick={()=>setView(v)}>{v}</button>)}</div></div>
 {view==='Day'&&<>{progress}<h4 className="section-label">Anytime tasks</h4><div className="all-day-list">{data.items.filter(t=>!t.deletedAt&&t.kind==='task'&&!t.date).map(t=><button className="secondary" key={t.id} onClick={()=>open(t,date)}>{t.title}</button>)}</div></>}
 {view==='Month'?<div className="month-grid">{labels.map(l=><div className="cal-heading" key={l}>{l}</div>)}{Array.from({length:42},(_,n)=>{const d=shift(monthStart,n),items=occurrenceItems(data.items,d);return <div className={`month-cell ${d.slice(5,7)!==date.slice(5,7)?'outside':''} ${d===date?'selected':''}`} key={d} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();drop(d,drag?mins(drag.time):540)}}><button className="month-day" aria-label={`Create event ${humanDate(d,true)}`} onClick={()=>create(d)}>{Number(d.slice(8))}</button>{items.map((t,j)=><button className="month-event" key={t.id+j} draggable onDragStart={()=>setDrag(t)} onClick={()=>open(t,d)} title={t.title}>{t.time?clockTime(t.time,data.settings.time)+' ':''}{t.title}</button>)}</div>})}</div>:
 <div className="calendar-wrap timeline-scroll" ref={scroller}><div className="calendar-head" style={{gridTemplateColumns:`54px repeat(${dates.length},minmax(0,1fr))`}}><div className="cal-heading">Time</div>{dates.map(d=><div className={`cal-heading ${d===iso()?'is-today':''}`} key={d}>{humanDate(d)}<div className="all-day-list">{occurrenceItems(data.items,d).filter(t=>!t.time).map((t,j)=><button key={t.id+j} className="month-event" draggable onDragStart={()=>setDrag(t)} onClick={()=>open(t,d)}>{t.title}</button>)}</div></div>)}</div>
 <div className="timeline-columns" style={{gridTemplateColumns:`54px repeat(${dates.length},minmax(0,1fr))`}}><div className="hour-labels">{Array.from({length:24},(_,h)=><div className="time-label" key={h}>{clockTime(hm(h*60),data.settings.time)}</div>)}</div>{dates.map(d=>{const items=occurrenceItems(data.items,d).filter(t=>t.time),lanes=calendarLanes(items.map(t=>({...t,id:t.id+':'+(t.occurrenceDate||d)})));return <div className="day-column" key={d}>{Array.from({length:96},(_,q)=><button className="quarter-slot" key={q} aria-label={`New event ${d} ${hm(q*15)}`} onClick={()=>create(d,hm(q*15))} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();drop(d,q*15)}}/>)}{items.map((t,j)=>{const lane=lanes.find(l=>l.id===t.id+':'+(t.occurrenceDate||d))||{lane:0,lanes:1},duration=Math.max(15,t.end?mins(t.end)-mins(t.time):60);return <div className={`calendar-event ${t.kind==='event'?'event-kind':''}`} key={t.id+j} role="button" tabIndex={0} aria-label={`Edit ${t.title}`} draggable onDragStart={()=>setDrag(t)} onClick={()=>open(t,d)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(t,d)}}} style={{top:mins(t.time)/60*56,height:duration/60*56-3,left:`calc(${lane.lane/lane.lanes*100}% + 2px)`,width:`calc(${100/lane.lanes}% - 4px)`}}><strong>{t.title}</strong><small>{clockTime(t.time,data.settings.time)}{t.end&&' – '+clockTime(t.end,data.settings.time)}</small><div className="resize-handle" role="separator" tabIndex={0} aria-label={`Resize ${t.title}`} aria-orientation="horizontal" onClick={e=>e.stopPropagation()} onPointerDown={e=>resize(e,t)} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();e.stopPropagation();const end=Math.min(1439,Math.max(mins(t.time)+15,mins(t.end||hm(mins(t.time)+60))+(e.key==='ArrowDown'?15:-15)));move(t,d,t.time,hm(end))}}}/></div>})}</div>})}</div></div>}
 <p className="calendar-note">Click an empty slot to create an event. Drag to move; use the lower edge to resize in 15-minute steps. Select an item to edit with the keyboard.</p></>
}
