import {useEffect,useState,type FormEvent,type ReactNode} from 'react';
import type {AppData,Item,Command} from '../shared/types';
import {validateItem,isDone} from '../shared/domain';
import {Icon,IconButton,offsets,reminderLabel} from './ui';
export interface EditSelection {item:Item;occurrenceDate:string;scope:'series'|'occurrence';isNew:boolean}
export default function Editor({selection,data,onSave,onClose,onDelete,onChangeDirty,busy}:{selection:EditSelection;data:AppData;onSave:(c:Command)=>Promise<boolean>;onClose:()=>void;onDelete:()=>void;onChangeDirty:(dirty:boolean)=>void;busy:boolean}){
 const [item,setItem]=useState<Item>(selection.item),[more,setMore]=useState(!selection.isNew),[error,setError]=useState('');
 useEffect(()=>{setItem(selection.item);setMore(!selection.isNew);setError('');onChangeDirty(false)},[selection]);
 useEffect(()=>{if(!selection.isNew){const current=data.items.find(i=>i.id===selection.item.id);if(current)setItem(i=>({...i,done:isDone(current,selection.occurrenceDate)}))}},[data.items]);
 const edit=<K extends keyof Item>(key:K,value:Item[K])=>{setItem(x=>({...x,[key]:value}));setError('');onChangeDirty(true)};
 const field=(icon:string,label:string,control:ReactNode,extra=false)=><label className={`field ${extra?'extra-field':''}`}><Icon name={icon}/><span>{label}</span>{control}</label>;
 const submit=async(e:FormEvent)=>{e.preventDefault();try{const valid=validateItem(item);if(valid.synced&&!valid.date)throw Error('Choose a date before adding this item to Google Calendar.');if(await onSave({type:'item.save',item:valid,scope:selection.scope,occurrenceDate:selection.occurrenceDate})){onChangeDirty(false);setError('')}}catch(err){setError((err as Error).message)}};
 return <section className="panel ornate editor"><div className="editor-header"><h3><Icon name="leaf"/>{selection.isNew?`New ${item.kind==='task'?'Task':'Event'}`:`${item.kind==='task'?'Task':'Event'} Details`}</h3><IconButton icon="x" label="Cancel editing" onClick={onClose}/></div><form id="task-form" className={more?'show-options':''} onSubmit={submit}>
 {!selection.isNew&&item.repeat!=='Never'&&<p className="scope-note">Editing {selection.scope==='occurrence'?`this occurrence · ${selection.occurrenceDate}`:'the entire series'}</p>}
 <input className="form-title" aria-label="Title" placeholder={item.kind==='task'?'Task title…':'Event title…'} value={item.title} onChange={e=>edit('title',e.target.value)} required maxLength={160}/>
 {field('calendar-days','Date',<input type="date" aria-label="Date" value={item.date} onChange={e=>edit('date',e.target.value)}/>)}
 {field('clock-3','Time',<input type="time" aria-label="Start time" value={item.time} onChange={e=>edit('time',e.target.value)} step="900"/>)}
 {field('hourglass','End time',<input type="time" aria-label="End time" value={item.end} onChange={e=>edit('end',e.target.value)} step="900"/>,item.kind==='task')}
 {field('tags','Category',<select aria-label="Category" value={item.category} onChange={e=>edit('category',e.target.value)}>{data.categories.map(c=><option key={c.id}>{c.name}</option>)}</select>)}
 {field('list-checks','Type',<select aria-label="Item type" value={item.kind} onChange={e=>edit('kind',e.target.value as Item['kind'])}><option value="task">Task</option><option value="event">Event</option></select>,true)}
 {field('bell','Reminder',<input className="toggle" type="checkbox" aria-label="Enable reminders" checked={item.reminderEnabled} onChange={e=>edit('reminderEnabled',e.target.checked)}/>)}
 {item.reminderEnabled&&<div className="reminder-options">{item.reminders.map(m=><button type="button" className="reminder-chip" key={m} aria-label={`Remove ${reminderLabel(m)}`} onClick={()=>edit('reminders',item.reminders.filter(x=>x!==m))}>{reminderLabel(m)} ×</button>)}<select aria-label="Add reminder" value="" onChange={e=>{if(e.target.value!=='')edit('reminders',Array.from(new Set([...item.reminders,Number(e.target.value)])).sort((a,b)=>a-b))}}><option value="">+ Add reminder</option>{offsets.filter(m=>!item.reminders.includes(m)).map(m=><option key={m} value={m}>{reminderLabel(m)}</option>)}</select>{!item.time&&<small>For date-only items, local alerts arrive at 9:00 AM.</small>}</div>}
 {field('calendar-check','Google Calendar',<input className="toggle" type="checkbox" aria-label="Sync to Google Calendar" checked={item.synced} disabled={!item.synced&&Object.keys(item.exceptions).length>0} onChange={e=>edit('synced',e.target.checked)}/>)}
 {Object.keys(item.exceptions).length>0&&!item.synced&&<p className="scope-note">Keep series with individual field edits local. Google supports syncing the whole series and skipped dates here.</p>}
 {selection.scope==='occurrence'&&item.synced&&<p className="scope-note">Complete or delete this occurrence below. Edit its fields in Google Calendar, or open Entire series here.</p>}
 {item.synced&&<><p className="scope-note">{data.google.connected?'Calendar event and phone reminders':'Saved locally until you connect Google in Settings.'}</p>{field('calendar','Calendar',<select aria-label="Google calendar for item" value={item.calendarId||data.settings.calendarId} onChange={e=>edit('calendarId',e.target.value)}><option value="">Default calendar</option>{data.google.calendars.map(c=><option key={c.id} value={c.id}>{c.summary}</option>)}</select>)}</>}
 {field('repeat-2','Repeat',<select aria-label="Repeat" value={item.repeat} onChange={e=>edit('repeat',e.target.value as Item['repeat'])} disabled={selection.scope==='occurrence'}>{['Never','Daily','Weekdays','Weekly','Monthly','Yearly','Custom'].map(v=><option key={v}>{v}</option>)}</select>,true)}
 {more&&item.repeat!=='Never'&&selection.scope==='series'&&<>{item.repeat==='Custom'&&field('repeat','Every (days)',<input aria-label="Repeat interval in days" type="number" min="1" max="365" value={item.interval} onChange={e=>edit('interval',Number(e.target.value))}/>)}{field('calendar-days','End repeat',<input aria-label="Recurrence end date" type="date" value={item.recurrenceEnd} onChange={e=>edit('recurrenceEnd',e.target.value)}/>)}{field('repeat','Count',<input aria-label="Occurrence count" type="number" min="1" max="10000" placeholder="Unlimited" value={item.recurrenceCount??''} onChange={e=>edit('recurrenceCount',e.target.value?Number(e.target.value):null)}/>)}</>}
 {field('flag','Priority',<select aria-label="Priority" value={item.priority} onChange={e=>edit('priority',e.target.value as Item['priority'])}>{['Low','Normal','High'].map(v=><option key={v}>{v}</option>)}</select>,true)}
 {item.kind==='event'&&field('map-pin','Location',<input aria-label="Location" value={item.location} onChange={e=>edit('location',e.target.value)} placeholder="Optional"/>,true)}
 {field('globe','Time zone',<input aria-label="Item time zone" value={item.timezone} onChange={e=>edit('timezone',e.target.value)} list="timezones"/>,true)}
 <button className="advanced-button" type="button" aria-expanded={more} onClick={()=>setMore(!more)}><Icon name={more?'chevron-up':'chevron-down'}/>{more?'Fewer task options':'More task options'}</button>
 <label className="notes-label" htmlFor="item-notes"><Icon name="notebook-pen"/> Notes</label><textarea className="notes" id="item-notes" value={item.notes} onChange={e=>edit('notes',e.target.value)} placeholder="A little detail for later…" maxLength={20000}/>
 {more&&selection.scope==='series'&&item.excludedDates.length>0&&<div className="scope-note">Hidden occurrences<div className="reminder-options">{item.excludedDates.map(d=><button className="reminder-chip" type="button" key={d} onClick={()=>edit('excludedDates',item.excludedDates.filter(x=>x!==d))}>Restore {d}</button>)}</div></div>}
 {error&&<p className="form-error" role="alert">{error}</p>}
 <button className="primary ornate" disabled={busy||selection.scope==='occurrence'&&item.synced} type="submit">{busy?'Saving…':selection.isNew?`Add ${item.kind==='task'?'Task':'Event'}`:'Save Changes'}</button>
 {!selection.isNew&&<div className="btn-row editor-actions"><button type="button" className="secondary" onClick={()=>onSave({type:'item.complete',id:item.id,date:selection.occurrenceDate})}>{item.done?'Uncomplete':'Complete'}</button><button className="danger" type="button" onClick={onDelete}><Icon name="trash-2"/>Delete</button></div>}
 <button type="button" className="cancel-edit" onClick={onClose}>Cancel</button><div className="editor-foot"><Icon name="hard-drive"/> Saved on this device{item.synced?` · ${data.google.connected?item.syncState:'Disconnected'}`:''}</div>
 </form></section>
}
